name: "Ccache for gh actions"
description: "A GitHub Action that speeds up compiling for C/C++ projects using ccache."
author: "Hendrik Muhs<hendrik.muhs@gmail.com>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  max-size:
    description: "Max size of the cache"
    default: "500M"
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success()"
branding:
  icon: "archive"
  color: "gray-dark"
